### Accessing/Changing specific elements, rows, columns


In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [5]:
# Get a specific element [r, c]
a[1, 5]

13

In [6]:
a[1, -2]

13

In [7]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [9]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [10]:
# Get a specific column
a[:, 5]

array([ 6, 13])

In [11]:
# Getting a little more fancy [row, startindex:endindex:stepsize]
a[0, 1:-1:2]  

array([2, 4, 6])

In [12]:
a[1, 1:-1:2]

array([ 9, 11, 13])

In [13]:
a[0, 1:5:2]

array([2, 4])

In [14]:
a[0, 1:6:3]

array([2, 5])

In [16]:
a[0, 0:7:3]

array([1, 4, 7])

In [18]:
# changing a specific value in the array
a[1,5] = 20
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [20]:
a[:,2] = 5 # entire 2nd column would be changed to 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [21]:
a[:,2] = [55,66] # can be a list of values but make sure the shape of array is maintained
a

array([[ 1,  2, 55,  4,  5,  6,  7],
       [ 8,  9, 66, 11, 12, 20, 14]])

**3D Example**

In [22]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
# Get specific element (work outside in)
b[0,1,1]

4

In [24]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [25]:
b[0,:,:]

array([[1, 2],
       [3, 4]])

In [27]:
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [ ]:
#replace
b[0,1,1] = 77
b

In [ ]:
b[0,:,:] = [[11,12],[13,14]] # make sure the shape of array is maintained
b

In [ ]:
b[:,:,1] = [[22,44],[66,88]] # make sure the shape of array is maintained
b

In [ ]:
b[:,1,:] = [[30,40],[70,80]] # make sure the shape of array is maintained
b

array([[[ 1,  2],
        [ 3, 77]],

       [[ 5,  6],
        [ 7,  8]]])

In [30]:
b[0,:,:] = [[11,12],[13,14]] # make sure the shape of array is maintained
b

array([[[11, 12],
        [13, 14]],

       [[ 5,  6],
        [ 7,  8]]])

In [31]:
b[:,:,1] = [[22,44],[66,88]] # make sure the shape of array is maintained
b

array([[[11, 22],
        [13, 44]],

       [[ 5, 66],
        [ 7, 88]]])

In [34]:
b[:,1,:] = [[30,40],[70,80]] # make sure the shape of array is maintained
b

array([[[11, 22],
        [30, 40]],

       [[ 5, 66],
        [70, 80]]])