### Mathematics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a *2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

**Notice all the actions are done on the original array, the result has the new value, the original array does not change**

In [8]:
b = np.array([1,0,1,0])
b

array([1, 0, 1, 0])

In [9]:
a+b

array([2, 2, 4, 4])

In [10]:
print(a)
print(b)

[1 2 3 4]
[1 0 1 0]


In [11]:
a ** 2

array([ 1,  4,  9, 16])

**Statistics**

In [13]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.min(stats)

1

In [15]:
np.max(stats)

6

In [16]:
np.max(stats, axis=1)

array([3, 6])

In [17]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [18]:
np.sum(stats, axis=1)

array([ 6, 15])